services:
  mysql:
    environment: 
      - MYSQL_RANDOM_ROOT_PASSWORD=1
    env_file:
      - mysql_env
    image: mysql:latest
    volumes: ['/var/data/wordpress/db:/var/lib/mysql']
    networks:
      - backend
  app:
    build:
      context: .
    ports:
      - 5000:5000
    environment:
      - USE_IN_MEMORY_STORAGE=0
      - MYSQL_HOST=mysql
    env_file: 
      - mysql_env
    networks:
      - backend

networks:
  backend:


version: '3.7'
